### PR TITLE
Etls

### PR DESCRIPTION
**Pull request by XpaMoBHuk**
still have 403 forbidden response on put and delete

### CODE REVIEW

**Comment by Tangerino** [comment]
Fixed!

**Comment by XpaMoBHuk** [comment]
merged all we have right now in master

6 out of 46 tests fails:

UpdateDevice Name - 403 forbidden

UpdateETL Name - 403 forbidden
DeleteETL - 403 forbidden

DeleteNFvalue - responds OK, but read still returns this NF value

UpdateThing - 403 forbidden
DeleteThing - 403 forbidden

ToDos:
1. solve the issues above, as we need devices working to develop dropbox
   and sensors
2. develop dropbox
3. develop sensors

not sure about new large calendar section, need to review first.

**Comment by Tangerino** [comment]
Thanks.
I'm back and fix the issues.
The calendar is big but all CRUD for the objects.
At the end, this calendar is used in the time series request.
Carlos

**Comment by Tangerino** [comment]
Eugene.
Could you run your tests again, I just want to be sure that we are in sync.
I've tested the ETL Update and it works for me.
Also, if you could guide me on how to run the tests myself it would speed
the process up.
As I've mentioned, my test window is empty in VS
Thanks
Carlos

**Comment by Tangerino** [comment]
Eugene.
My comments below.
I have just upgraded the service.
Carlos

**Comment by XpaMoBHuk** [comment]
Carlos,

Just executed all test - issues seems all the same. Can I have 403 response
when I'm trying to update read only property?

**Comment by XpaMoBHuk** [comment]
Delete NF Value works, but it doesn't delete anything for me - item comes
back in a list after read.

**Comment by Tangerino** [comment]
I've made the tests using Python and they are looking good this morning. I
also have deployed a new service version
Can you show me how I make your project run in my VS instance please? So I
can test locally.
I'll activate the debug mode and check if I can figure out what is going on.
Thanks
Carlos

**Comment by XpaMoBHuk** [comment]
I'll try to describe now how to debug it, but it's the same code running
for all requests. If it doesn't work - it won't  work for everything. So
it's just a matter of post data I'm using.

So deleting NF value test does:

_LOGIN_ request:
https://wimd.io:443/v2/account/login
POST
{\"password\":\"XpaMoBHuk\",\"email\":\"XpaMoBHuk\"}

response:
{\n\t\"apikey\":\t\"ec3695b29fca3008e1558e7d7fcf070ae8705b1d58f43b5a453f91168790ca3b\",\n\t\"permissions\":\t255,\n\t\"userId\":\t\"a5865a97-dd15-11e5-8db7-04017fd5d401\"\n}

*CREATE PLACE  *request:
https://wimd.io:443/v2/place
POST
{\"name\":\"Name b117f49b\",\"description\":\"Description b117f49b\"}

response:
[{\"id\":\"1b2f0e2f-e1f5-11e5-8e73-04017fd5d401\",\"name\":\"Name
b117f49b\",\"description\":\"Description b117f49b\"}]

_CREATE NF_ request:
https://wimd.io:443/v2/place/1b2f0e2f-e1f5-11e5-8e73-04017fd5d401/nf
POST
{\"name\":\"Name a6fe7130\",\"description\":\"Description
a6fe7130\",\"unit\":\"Unit a6fe7130\",\"aggregation\":2,\"operation\":0}

response:
[{\n\t\t\"id\":\t\"45e898ca-e1f5-11e5-8e73-04017fd5d401\",\n\t\t\"name\":\t\"Name
a6fe7130\",\n\t\t\"aggregation\":\t2,\n\t\t\"operation\":\t0,\n\t\t\"unit\":\t\"Unit
a6fe7130\",\n\t\t\"description\":\t\"Description a6fe7130\"\n\t}]

_CREATE NF VALUE_ request:
https://wimd.io:443/v2/nf/45e898ca-e1f5-11e5-8e73-04017fd5d401/value
POST
{\"ts\":\"2016-03-04T21:39:36+11:00\",\"value\":\"13653\"}

response:
[{\n\t\t\"id\":\t\"bad16801-dfac-11e5-8e73-04017fd5d401\",\n\t\t\"name\":\t\"Name
aa7b48e7\",\n\t\t\"aggregation\":\t2,\n\t\t\"operation\":\t0,\n\t\t\"unit\":\t\"Unit
aa7b48e7\",\n\t\t\"description\":\t\"Description aa7b48e7\"\n\t}]

*DELETE NF VALUE *request:
https://wimd.io:443/v2/nf/45e898ca-e1f5-11e5-8e73-04017fd5d401/value/2016-03-04T21:39:36.0000000+11:00
DELETE

response:
{\"status\":\"OK\",\"code\":200}

_READ NF VALUES_ request:
https://wimd.io:443/v2/nf/45e898ca-e1f5-11e5-8e73-04017fd5d401/values
GET

response:
[{\n\t\t\"ts\":\t\"2016-03-04 21:39:36\",\n\t\t\"value\":\t13653\n\t}]

**Comment by XpaMoBHuk** [comment]
Here is potential issue: look at the response object for NF value create:

[{
"id": "9133aafb-dfad-11e5-8e73-04017fd5d401",
"name": "Name ea55837a",
"aggregation": 2,
"operation": 0,
"unit": "Unit ea55837a",
"description": "Description ea55837a"
}]

This is not NF value, this is NF itself

**Comment by Tangerino** [comment]
Fixed!
Now will just return OK since you need the I don't and the time stamp to
change it later (no I don't for an individual value)

**Pull request merged**
